export const type = {
    START_SAVE_PROFIL: "START_SAVE_PROFIL",
    SUCCESS_SAVE_PROFIL: "SUCCESS_SAVE_PROFIL",
    FAILURE_SAVE_PROFIL: "FAILURE_SAVE_PROFIL",
    START_LOGIN_PROFIL: "START_LOGIN_PROFIL",
    SUCCESS_LOGIN_PROFIL: "SUCCESS_LOGIN_PROFIL",
    FAILURE_LOGIN_PROFIL: "FAILURE_LOGIN_PROFIL",
    START_LOGOUT:"START_LOGOUT",
    SUCCESS_LOGOUT:"SUCCESS_LOGOUT",
    FAILURE_LOGOUT:"FAILURE_LOGOUT",
    START_CHANGE_PASSWORD:"START_CHANGE_PASSWORD",
    SUCCESS_CHANGE_PASSWORD:"SUCCESS_CHANGE_PASSWORD",
    FAILURE_CHANGE_PASSWORD:"FAILURE_CHANGE_PASSWORD"
};